name: Pulumi Deployment

on:
  push:
    branches:
      - pe-pattern-pulumi   # Deploy on push to main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
                "clientId": "657f814b-9667-4e5a-a3d4-3f264ff38bb4",
                "clientSecret": "7Rl8Q~EN-qc.DDOlXI6KrkJkpEhfGVa392YsGcwG",
                "subscriptionId": "05276564-4a5f-40d6-b156-3ed5768e3bf3",
                "tenantId": "8196ddea-f6c5-4044-8209-53ad1fdaebbf",
                "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
                "resourceManagerEndpointUrl": "https://management.azure.com/",
                "activeDirectoryGraphResourceId": "https://graph.windows.net/",
                "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
                "galleryEndpointUrl": "https://gallery.azure.com/",
                "managementEndpointUrl": "https://management.core.windows.net/"
              }
      # - name: Set environment variables
      #   run: |
      #     echo "ARM_CLIENT_ID=657f814b-9667-4e5a-a3d4-3f264ff38bb4" >> $GITHUB_ENV
      #     echo "ARM_CLIENT_SECRET=7Rl8Q~EN-qc.DDOlXI6KrkJkpEhfGVa392YsGcwG" >> $GITHUB_ENV
      #     echo "ARM_SUBSCRIPTION_ID=05276564-4a5f-40d6-b156-3ed5768e3bf3" >> $GITHUB_ENV
      #     echo "ARM_TENANT_ID=8196ddea-f6c5-4044-8209-53ad1fdaebb" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # match your Pulumi project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Infrastructure/pulumi/requirements.txt

      - name: Set up Pulumi CLI
        uses: pulumi/actions@v5
        with:
          pulumi-version: latest

      - name: Login to Pulumi
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}

      - name: Select stack
        run: |
          pulumi stack select rakshitha-mayya/aks-foundation/dev --cwd Infrastructure/pulumi || pulumi stack init rakshitha-mayya/aks-foundation/dev --cwd Infrastructure/pulumi
          pulumi stack change-secrets-provider default --cwd Infrastructure/pulumi

      - name: Pulumi preview
        run: pulumi preview --cwd Infrastructure/pulumi

      # - name: Pulumi up
      #   run: pulumi up --yes --cwd Infrastructure/pulumi
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: us-east-1
